image: node:latest

stages:
  - install
  - test

install_react:
  stage: install
  script:
    - yarn install
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/


test_react:
  stage: test
  needs: [install_react]
  script:
    - echo "Testing project"
    - yarn test -- --coverage --watchAll=false
    - echo "Test successful"
